spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/led-doc-db
    username: postgres
    password: root
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
  graphql:
    graphiql:
      enabled: true
    cors:
      allow-credentials: true
      allowed-origins:
        - http://localhost:4200
        - http://localhost:8081
urx:
  language: en
  develop-mode: true
  security:
    enable-graphql: true
    permit-requests:
      - /graphiql
      - /favicon.ico
    permit-graphql-methods:
      - query.IntrospectionQuery
      - mutation.signUp
      - mutation.signIn
      - mutation.changePassword
    develop:
      enable: true
      jwt-user-name: fernnypay95
      jwt-payload: 72eefa0a-4813-4d6e-b77f-c13ecf457543
      jwt-authorities:
        - ROLE_ADMIN